import { Job } from "../job-types"


export const MOCK_JOBS: Job[] = [
    {
        id: "pb-26-0001",
        code: "PB-26-0001",
        status: "Active",
        address: "7201 Wesley Ln",
        clientName: "Miller Residence",
        jobtreadNumber: "JT-44821",
        superintendentInitials: "JM",
        superintendentName: "Jordan Mills",
        rightOnScore: 92,
        itemsComplete: 13,
        itemsTotal: 37,
        openCount: 1,
        overdueCount: 0,
        readyForReviewCount: 1,
        phaseProgress: [
            { phase: "Foundation", completed: 4, total: 4 },
            { phase: "Framing", completed: 6, total: 8 },
            { phase: "Tile / Waterproofing", completed: 3, total: 6 },
            { phase: "Electrical Rough", completed: 0, total: 7 },
            { phase: "Final Punch", completed: 0, total: 12 },
        ],
        recentLockedInspections: [
            {
                phase: "Tile / Waterproofing",
                subtitle: "Tile — HydroBlok Waterproofing",
                lockedDate: "2026-07-23",
                inspector: "JM",
            },
            {
                phase: "Foundation",
                subtitle: "Foundation — Footings & Slab",
                lockedDate: "2026-07-15",
                inspector: "JM",
            },
        ],
    },
    {
        id: "pb-26-0014",
        code: "PB-26-0014",
        status: "Punch List",
        address: "412 Ridgeline Dr",
        clientName: "Harper Custom Homes",
        jobtreadNumber: "JT-44907",
        superintendentInitials: "DL",
        superintendentName: "Dana Lee",
        rightOnScore: 78,
        itemsComplete: 27,
        itemsTotal: 37,
        openCount: 2,
        overdueCount: 1,
        readyForReviewCount: 0,
        phaseProgress: [
            { phase: "Foundation", completed: 4, total: 4 },
            { phase: "Framing", completed: 8, total: 8 },
            { phase: "Tile / Waterproofing", completed: 6, total: 6 },
            { phase: "Electrical Rough", completed: 7, total: 7 },
            { phase: "Final Punch", completed: 2, total: 12 },
        ],
        recentLockedInspections: [
            {
                phase: "Electrical Rough",
                subtitle: "Electrical — Panel & Rough Wiring",
                lockedDate: "2026-07-20",
                inspector: "DL",
            },
        ],
    },
    {
        id: "pb-26-0022",
        code: "PB-26-0022",
        status: "On Hold",
        address: "99 Oakmont Ct",
        clientName: "Vance Development",
        jobtreadNumber: "JT-45010",
        superintendentInitials: "JM",
        superintendentName: "Jordan Mills",
        rightOnScore: 64,
        itemsComplete: 2,
        itemsTotal: 37,
        openCount: 1,
        overdueCount: 0,
        readyForReviewCount: 0,
        phaseProgress: [
            { phase: "Foundation", completed: 2, total: 4 },
            { phase: "Framing", completed: 0, total: 8 },
            { phase: "Tile / Waterproofing", completed: 0, total: 6 },
            { phase: "Electrical Rough", completed: 0, total: 7 },
            { phase: "Final Punch", completed: 0, total: 12 },
        ],
        recentLockedInspections: [],
    },
    {
        id: "pb-25-0198",
        code: "PB-25-0198",
        status: "Completed",
        address: "3300 Camden Blvd",
        clientName: "Northgate Partners",
        jobtreadNumber: "JT-43119",
        superintendentInitials: "AR",
        superintendentName: "Alex Reyes",
        rightOnScore: 97,
        itemsComplete: 37,
        itemsTotal: 37,
        openCount: 0,
        overdueCount: 0,
        readyForReviewCount: 0,
        phaseProgress: [
            { phase: "Foundation", completed: 4, total: 4 },
            { phase: "Framing", completed: 8, total: 8 },
            { phase: "Tile / Waterproofing", completed: 6, total: 6 },
            { phase: "Electrical Rough", completed: 7, total: 7 },
            { phase: "Final Punch", completed: 12, total: 12 },
        ],
        recentLockedInspections: [
            {
                phase: "Final Punch",
                subtitle: "Final Punch — Full Walkthrough",
                lockedDate: "2026-06-30",
                inspector: "AR",
            },
        ],
    },
]

export const PHASE_TEMPLATES = ["Foundation", "Framing", "Tile / Waterproofing", "Electrical Rough", "Final Punch"] as const

export type PhaseTemplate = (typeof PHASE_TEMPLATES)[number]

export const PHASE_CHECKLIST_LABELS: Record<PhaseTemplate, string[]> = {
    Foundation: [
        "Footings/forms verified before pour",
        "Anchor bolts/hold downs placed correctly",
        "Vapor barrier and slab prep documented",
        "Foundation walls cured before backfill",
    ],
    Framing: [
        "Wall plates and studs to spec",
        "Headers sized correctly",
        "Hardware and connectors installed",
        "Shear nailing pattern verified",
        "Blocking and fire stops in place",
        "Window/door rough openings sized correctly",
        "Roof framing and sheathing complete",
        "Wall framing plumb and per plan",
    ],
    "Tile / Waterproofing": [
        "Substrate slope verified",
        "Waterproof membrane fully cured",
        "Seams and penetrations sealed",
        "Tile layout matches plan",
        "Grout cure time documented",
        "Shower pan flood tested",
    ],
    "Electrical Rough": [
        "Panel schedule matches plan",
        "Circuit runs sized correctly",
        "Boxes secured and fire-rated where required",
        "Grounding and bonding complete",
        "Rough-in inspection tags applied",
        "GFCI/AFCI locations confirmed",
        "Low-voltage runs separated from power",
    ],
    "Final Punch": [
        "All prior deficiencies closed",
        "Fixtures and finish hardware installed",
        "Final grading and drainage verified",
        "Life safety systems tested",
        "Paint and trim touch-ups complete",
        "Appliances installed and tested",
        "Exterior finishes complete",
        "Doors and windows operate correctly",
        "Punch list signed off by client",
        "Utility meters confirmed active",
        "Site cleaned and debris removed",
        "Certificate of occupancy documentation complete",
    ],
}

export const VENDOR_OPTIONS = ["Unassigned", "Miller Concrete Co.", "Wesley Framing Crew", "In-House Inspector"]